# Generated by Django 5.1.1 on 2024-09-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('city_picture', models.ImageField(null=True, upload_to='static/city')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('title_link', models.CharField(max_length=150, null=True)),
                ('posted_data', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='static/slider/')),
                ('title', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='video_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_headline', models.CharField(max_length=400, null=True)),
                ('news_descriptions', models.TextField(null=True)),
                ('video_link', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=400, null=True)),
                ('news_descriptions', models.TextField()),
                ('posted_data', models.DateField()),
                ('news_picture', models.ImageField(null=True, upload_to='static/news/')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('news_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_city')),
            ],
        ),
    ]
