# Generated by Django 5.1.1 on 2024-09-23 06:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_city_tbl_jobs_tbl_slider_video_news_tbl_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_news',
            name='posted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_news',
            name='news_descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video_news',
            name='news_descriptions',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
